

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru

  pig-procesador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pig
    volumes:
      - ./data:/opt/pigjob/data
      - ./pig:/opt/pigjob/pig
    stdin_open: true
    tty: true
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
